name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests before deployment
      run: |
        python manage.py migrate
        python -m pytest -v

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
      env:
        DJANGO_SETTINGS_MODULE: django_api_boilerplate.settings
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Verify deployment readiness
      run: |
        echo "✅ All tests passed"
        echo "✅ Static files collected"
        echo "✅ Application is ready for deployment"

    # Example deployment notification
    - name: Deployment notification
      if: success()
      run: |
        echo "Deployment successful! 🚀"
        echo "Version: ${{ github.sha }}"
        echo "Environment: production"
